#!/usr/bin/env bash

set -e

PROGNAME="$(basename "${0}")"
function usage() {
cat <<EOF
Usage:
${PROGNAME} [-h|--help] [--directory <DIR>] [--review <LLVM-REVIEW>] [--url <URL>]

--review        When used, the diff being applied is the one associated to that
                Phabricator review.

--diff-url      When used, this exact URL is used to fetch the diff instead of
                inferring it from the review number. This can be used for example
                when a separate diff was uploaded on Phabricator and a review
                was created from it: in that case, trying to infer the diff from
                the review number will fail.

--directory     Use that directory as the root when applying the patch. In other
                words, all file paths in the diff are relative to that directory.
EOF
}

for arg in $@; do
    if [[ "${arg}" == "-h" || "${arg}" == "--help" ]]; then
        usage
        exit 0
    fi
done

while [[ $# -gt 0 ]]; do
    case ${1} in
        --directory)
            directory="${2}"
            shift
            shift
            ;;
        --diff-url)
            url="${2}"
            shift
            shift
            ;;
        --review)
            url="https://reviews.llvm.org/${2}?download=true"
            shift
            shift
            ;;
    esac
done

if [ -z ${directory+x} ]; then
    directory_string=""
else
    directory_string="-p0 --directory ${directory}"
fi

wget --quiet -O - "${url}" | git apply --reject ${directory_string}
