#!/usr/bin/env bash

cat - | grep -e '-cc1' |
        grep -E -e '-std(=|\s+).*' |
        sed -E -e 's/.*-std(=|\s+)([^ "]*).*/\2/' |
        awk '{xs[$1]++} END {for (f in xs) { printf "%s %s\n", xs[f], f }}' |
        sort -n -r |
        awk '
        {xs[$2] = $1; total+=$1}
        END {
        for (x in xs) {
            n=xs[x];
            if (n > 2) {
                printf "%4.1f%% %s\n", n/total*100, x
            }
        }
        }' |
        sort -n -r -k 2
