#!/usr/bin/env bash

#
# Running this script will start a Docker container with a recent-ish Clang
# and a recent CMake that can be used to emulate the environment used by
# libc++'s Linux builders on BuildKite.
#

set -e

MONOREPO_ROOT="$(git rev-parse --show-toplevel)"
LIBCXX_IMAGE=$(docker build -q ${MONOREPO_ROOT}/libcxx/utils/ci)
docker run -it --volume "${MONOREPO_ROOT}:/llvm" --workdir "/llvm" "${LIBCXX_IMAGE}" bash
