#!/usr/bin/env bash

#
# Running this script will start a Docker container with a recent-ish GCC and
# a recent CMake that can be used to build libc++ on Ubuntu.
#

set -e

if [[ "${1}" == "--setup-linux" ]]; then
    apt-get update
    apt-get install -y build-essential software-properties-common less wget git ninja-build python
    add-apt-repository -y ppa:ubuntu-toolchain-r/test
    apt-get update
    apt-get install -y gcc-9 g++-9

    # Install a recent CMake
    yes | apt-get purge cmake
    wget https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2-Linux-x86_64.sh -O /tmp/install-cmake.sh
    bash /tmp/install-cmake.sh --prefix=/usr --exclude-subdir --skip-license
    cmake --version

    git config --global user.email "ldionne@apple.com"
    git config --global user.name "Louis Dionne"

    bash
else
    docker pull ubuntu:16.04
    docker run --interactive --tty --rm \
               --volume "${HOME}/work/llvm":/llvm \
               --volume "$(dirname "${0}")":/tmp/.bin \
               --workdir /llvm ubuntu:16.04 \
               "/tmp/.bin/$(basename "${0}")" --setup-linux
fi
