#!/usr/bin/env bash

set -e

PROGNAME="$(basename "${0}")"
function usage() {
cat <<EOF
Usage:
${PROGNAME} [-h|--help] <build-directory> tests...

Shortcut to run the libc++ tests with Lit.

<build-directory>  The path to the build directory to use for building the library.
tests...           Paths of the tests to run. Those are paths relative to '<monorepo-root>/libcxx/test'.
EOF
}

for arg in $@; do
    if [[ "${arg}" == "-h" || "${arg}" == "--help" ]]; then
        usage
        exit 0
    fi
done

if [[ $# -lt 1 ]]; then
    usage
    exit 1
fi

build_dir="$(realpath "${1}")"
shift

cmake --build "${build_dir}" --target cxx-test-depends
(cd libcxx/test && "${build_dir}/bin/llvm-lit" -sv ${@})
