#!/usr/bin/env bash

##
## This script performs the initial setup.
##

set -e
export DOTFILES="$(pwd)"

if [[ ! -d "$DOTFILES/custom" || ! -d "$DOTFILES/setup" ]]; then
    echo "you must run this script from the root of the project"
    exit 1
fi

source $DOTFILES/setup/utils


info "performing initial setup"
$DOTFILES/setup/install_dotfiles
$DOTFILES/setup/setup_sublime_preferences

# If we are on a mac, set OS X preferences and install Homebrew formulae.
if [ "$(uname -s)" == "Darwin" ]; then
    $DOTFILES/setup/set_osx_preferences
    $DOTFILES/setup/install_homebrew_formulae
fi
success "everything is done!"
