#!/usr/bin/env bash

##
## This script symlinks the dotfiles into $HOME.
##

source $DOTFILES/setup/utils


install_dotfiles() {
    for symlink_file in $(find $DOTFILES/custom -maxdepth 2 -name \*.symlink)
    do
        local dotfile="$HOME/.$(basename "${symlink_file%.*}")"
        link_files "$symlink_file" "$dotfile"
    done
}

info "installing dotfiles"
install_dotfiles && success "installed dotfiles"
