#!/usr/bin/env bash

##
## This installs Homebrew and several formulae.
##

source $DOTFILES/setup/setup_utils
set -e


install_homebrew() {
    if ! is_in_path brew; then
        info "installing Homebrew"
        ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
        success "installed Homebrew"
    else
        info "Homebrew is already installed, skipping this step"
    fi
}

install_formula() {
    local formula="$1"
    if ! brew list | grep "$formula" &>/dev/null; then
        info "installing $formula"
        brew install "$formula"
        success "installed $formula"
    else
        success "$formula already installed with Homebrew"
    fi
}

install_formulae() {
    local formulae=(
        grc
        coreutils
        git
        hub
        python3
        cmake
        libusb  # dependency of DisplayLinkManager (3rd screen)
    )

    if ! is_in_path brew; then
        fail "Homebrew must be installed before we can install formulae"
    fi

    for formula in "${formulae[@]}"; do
        install_formula "$formula"
    done
}

install_homebrew && install_formulae
