#!/usr/bin/env bash

##
## Utilities for performing the initial setup.
##


info() {
    printf "  [ \033[00;34m..\033[0m ] $1\n"
}

user() {
    printf "\r  [ \033[0;33m?\033[0m ] $1\n"
}

success() {
    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail() {
    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
    exit 127
}

is_in_path() {
    command -v "${1}" &>/dev/null || return 1
    return 0
}

link_files() {
    local src="$1"
    local dst="$2"

    ln -s "$src" "$dst"
    success "linked $src to $dst"
}
